[package]
name = "nidrs-macro"
version = "0.2.1"
authors = ["WumaCoder <wumacoder@gmail.com>"]
description = "a nidrs macro."
keywords = ["nidrs"]
categories = ["development-tools"]
publish = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
nidrs-extern = { workspace = true }

proc-macro2 = "1.0.86"
syn = { version = "2.0.75", features = ["full"] }
syn-serde = { version = "0.3.1", features = ["json"] }
quote = "1.0.36"
once_cell = "1.19.0"

syn-args = { workspace = true, features = ["loose_mode"] }
syn-args-derive = { workspace = true }
