[package]
name = "nidrs-extern"
version = "0.2.1"
authors = ["WumaCoder <wumacoder@gmail.com>"]
description = "Nidrs external library."
keywords = ["nidrs", "axum", "http", "web", "framework"]
categories = ["network-programming", "asynchronous", "web-programming::http-server", "web-programming::websocket"]
publish = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
axum = { version = "0.7.4", features = ["json", "ws"] }
axum-extra = { version = "0.9.2", features = ["typed-header", "typed-routing"] }
tokio = { version = "1.36.0", features = ["full"] }
tower = "0.5.0"
colored = "2"
anyhow = "1.0.82"
thiserror = "1.0.58"
serde_json = "1.0.115"
serde = "1.0.197"
once_cell = "1.19.0"
globset = "0.4.14"

proc-macro2 = "1.0.86"
syn = { version = "2.0.75", features = ["full"] }
syn-serde = { version = "0.3.1", features = ["json"] }
quote = "1.0.36"

syn-args = { workspace = true, features = ["loose_mode"] }
syn-args-derive = { workspace = true }

[features]
default = ["tower", "serde"]
tower = ["tower/full"]
serde = ["serde/derive"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
