[package]
name = "nidrs"
version = "0.4.0"
authors = ["WumaCoder <wumacoder@gmail.com>"]
description = "Nidrs is a web framework based on axum and tokio."
keywords = ["nidrs", "axum", "http", "web", "framework"]
categories = ["network-programming", "asynchronous", "web-programming::http-server", "web-programming::websocket"]
publish = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
nidrs-macro = { workspace = true }
nidrs-extern = { workspace = true }
nidrs-valid = { workspace = true, optional = true }
nidrs-openapi = { workspace = true, optional = true }

[features]
default = ["tower", "serde"]
tower = ["nidrs-extern/tower"]
serde = ["nidrs-extern/serde"]
valid = ["nidrs-valid"]
openapi = ["nidrs-openapi"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
