[package]
name = "nidrs-openapi-macro"
version = "0.2.0"
authors = ["WumaCoder <wumacoder@gmail.com>"]
description = "a openapi macro."
keywords = ["nidrs"]
categories = ["development-tools"]
publish = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
nidrs-extern = { workspace = true } # version: "0.2.0"

proc-macro2 = "1.0.79"
syn = { version = "2.0.53", features = ["full"] }
syn-args = { workspace = true }
syn-serde = { version = "0.3", features = ["json"] }
quote = "1.0.35"
once_cell = "1.19.0"
